# Generated by Django 5.0.6 on 2024-06-01 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inst_emp_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='choice_list',
            fields=[
                ('choice_list_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_1', models.TextField()),
                ('choice_2', models.TextField()),
                ('choice_3', models.TextField()),
                ('choice_4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='exam_info',
            fields=[
                ('exam_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_title', models.CharField(max_length=100)),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='fileUploads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc', models.FileField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='otp_table',
            fields=[
                ('otp_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('member_email', models.EmailField(max_length=256)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('otp_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='question_reference',
            fields=[
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_no', models.CharField(max_length=5)),
                ('chapter_no', models.CharField(max_length=5)),
                ('topic_no', models.CharField(max_length=5)),
                ('sub_topic_no', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('answer', models.TextField(default='No answer submitted')),
                ('question_status', models.CharField(max_length=100)),
                ('choice_list_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qBank.choice_list')),
                ('submitter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reference_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qBank.question_reference')),
            ],
        ),
        migrations.CreateModel(
            name='exam_question_history',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qBank.exam_info')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qBank.question')),
            ],
        ),
    ]
