# Generated by Django 5.0.6 on 2024-06-12 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qBank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_table',
            name='expire_time',
            field=models.DateTimeField(default=datetime.date(2024, 6, 12)),
        ),
        migrations.AddField(
            model_name='otp_table',
            name='otp_status',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.AddField(
            model_name='otp_table',
            name='purpose',
            field=models.CharField(default='multiple', max_length=100),
        ),
    ]
