# Generated by Django 5.0.6 on 2024-06-12 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qBank', '0002_otp_table_expire_time_otp_table_otp_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_table',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 14, 14, 52, 652400)),
        ),
    ]
