# Generated by Django 5.0.6 on 2024-06-12 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qBank', '0003_alter_otp_table_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_table',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 9, 5, 5, 702344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp_table',
            name='otp_code',
            field=models.CharField(max_length=8),
        ),
    ]
