# Generated by Django 5.0.6 on 2024-06-28 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qBank', '0005_remove_question_choice_list_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_table',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 28, 12, 46, 29, 656334, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
