# Generated by Django 5.0.6 on 2024-06-28 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qBank', '0008_alter_otp_table_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_table',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 28, 12, 55, 24, 129397, tzinfo=datetime.timezone.utc)),
        ),
    ]
