# Generated by Django 5.0.6 on 2024-06-30 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qBank', '0009_alter_otp_table_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_info',
            name='exam_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exam_question_history',
            name='history_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otp_table',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 3, 33, 7, 287133, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otp_table',
            name='otp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
