# Generated by Django 5.0.6 on 2024-06-30 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qBank', '0011_alter_member_member_id_alter_otp_table_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_table',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 3, 35, 24, 466632, tzinfo=datetime.timezone.utc)),
        ),
    ]
