# Generated by Django 5.0.6 on 2024-06-30 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qBank', '0012_alter_otp_table_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_table',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 3, 37, 42, 769150, tzinfo=datetime.timezone.utc)),
        ),
    ]
