# Generated by Django 5.0.6 on 2024-06-30 04:30

import datetime
import qBank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qBank', '0014_alter_member_member_id_alter_otp_table_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_table',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 4, 32, 20, 901707, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=qBank.models.genID, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
