# Generated by Django 5.0.6 on 2024-07-01 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qBank', '0018_alter_otp_table_expire_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_table',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 3, 17, 515646, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 16, 1, 17, 515646, tzinfo=datetime.timezone.utc)),
        ),
    ]
