"""
Django settings for core_files project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nfk&5-yxz+94%9d3d+)bbp52k3b8#53i1ybck8e8u7odftvw=x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # if css is lost we need 'pip install whitenoise' and add 'whitenoise.middleware.WhiteNoiseMiddleware' in middleware

ALLOWED_HOSTS = ['*'] #This is the list of the hostnames that the server will accept requests from. '*' means all hostnames are accepted

AUTH_USER_MODEL = 'qBank.member'    #this is the custom user model that we have created

# AUTH_USER_MODEL = 'qBank.user'

# Application definition

INSTALLED_APPS = [
    
    # third party apps
    "admin_interface", 
    "colorfield", #for color field in admin interface
    # 'django_quill', #for rich text editor data management
    'widget_tweaks', #for form field customization
    # 'latexify', #for latex rendering

    

    # system apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # user apps
    'qBank',

    
]

########################################  Custom user model & login backend  ########################################

AUTH_USER_MODEL = 'qBank.member'    #this is the custom user model that we have created
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.AllowAllUsersModelBackend',
    # 'qBank.backends.CaseInsensitiveModelBackend',   deprecated           
)

##############################################  ++++++++++++++++++++  ##############################################

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #this is the middleware that will serve the static files
]

ROOT_URLCONF = 'core_files.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'qBank.context_processors.custom_context_variables', #this is the custom context processor that we have created
            ],
        },
    },
]



WSGI_APPLICATION = 'core_files.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = 'aqman@maksud.xyz'
EMAIL_HOST_PASSWORD = 'aqman@2024!'
EMAIL_PORT = 465
EMAIL_HOST = 'mail.maksud.xyz'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dacca'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



#This is the path to the static files from where its collected initially  
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static_user')] 

#This is the path to the static files from where its collected initially  
STATIC_ROOT=os.path.join(BASE_DIR,'static_system') #This is the path to the static files are stored to used by the server

#This is the url subpath where the static system files are found by the server 
# STATIC_URL = '/static_system/'
STATIC_URL = '/static_user/' #just for development purpose
#STATIC_URL = '/newapp/static_system/' is when the app is running on a subpath of the server www.maksud.xyz/newapp

#media management
MEDIA_URL = '/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media') #This is the path to the media files are stored to used by the server

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
